kernel: fix OpenSSL include-related build failure
It fails like this:

fatal error: openssl/bio.h: No such file or directory

due to new dependency in newer kernels.

Add openssl-native as explicit dependency to fix that.

Signed-off-by: Alex Tereschenko <alext.mkrs@gmail.com>