u-boot-internal.inc: Do not check the SHA validation for branch
Specifying the branch name and having the tag set as SRCREV makes bitbake error out:

WARNING: u-boot-edison-v2017.03-r0 do_fetch: Failed to fetch URL git://github.com/andy-shev/u-boot.git;branch=edison;protocol=https, attempting MIRRORS if available
ERROR: u-boot-edison-v2017.03-r0 do_fetch: Fetcher failure: Unable to find revision 506270615cf8e567b0b153bd5c2de47c35f671f8 in branch edison even from upstream
ERROR: u-boot-edison-v2017.03-r0 do_fetch: Fetcher failure for URL: 'git://github.com/andy-shev/u-boot.git;branch=edison;protocol=https'. Unable to fetch URL from any source.
ERROR: u-boot-edison-v2017.03-r0 do_fetch: Function failed: base_do_fetch

From http://git.yoctoproject.org/cgit.cgi/poky/plain/bitbake/lib/bb/fetch2/git.py:

- nobranch
   Don't check the SHA validation for branch. set this option for the recipe
   referring to commit which is valid in tag instead of branch.
   The default is "0", set nobranch=1 if needed.

Signed-off-by: Florin Sarbu <florin@resin.io>